<?php

class PlayerTableSeeder extends Seeder
{

    public function run()
    {
        $players = $this->load_array();

        foreach($players as $player){
            Player::create($player);
        }
    }

    private function load_array(){
        $now = date('Y-m-d H:i:s');

        return array(
            array('name' => 'Jimmy Butler', 'team' => 'Chicago Bulls', 'position' => 'SG', 'college' => 'Marquette', 'number' => '21', 'experience' => '2', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Tony Snell', 'team' => 'Chicago Bulls', 'position' => 'SG', 'college' => 'New Mexico', 'number' => '20', 'experience' => '0', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Kirk Hinrich', 'team' => 'Chicago Bulls', 'position' => 'SG', 'college' => 'Kansas', 'number' => '12', 'experience' => '10', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Derrick Rose', 'team' => 'Chicago Bulls', 'position' => 'PG', 'college' => 'Memphis', 'number' => '1', 'experience' => '4', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Mike Dunleavy', 'team' => 'Chicago Bulls', 'position' => 'SF', 'college' => 'Duke', 'number' => '34', 'experience' => '11', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Mike James', 'team' => 'Chicago Bulls', 'position' => 'PG', 'college' => 'Duquesne', 'number' => '0', 'experience' => '11', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Carlos Boozer', 'team' => 'Chicago Bulls', 'position' => 'PF', 'college' => 'Duke', 'number' => '5', 'experience' => '11', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Ronnie Brewer', 'team' => 'Chicago Bulls', 'position' => 'SF', 'college' => 'Arkansas', 'number' => '10', 'experience' => '7', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Jimmer Fredette', 'team' => 'Chicago Bulls', 'position' => 'PG', 'college' => 'Brigham Young', 'number' => '32', 'experience' => '2', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Nazr Mohammed', 'team' => 'Chicago Bulls', 'position' => 'C', 'college' => 'Kentucky', 'number' => '48', 'experience' => '15', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Taj Gibson', 'team' => 'Chicago Bulls', 'position' => 'PF', 'college' => 'USC', 'number' => '22', 'experience' => '4', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'D.J. Augustin', 'team' => 'Chicago Bulls', 'position' => 'PG', 'college' => 'Texas', 'number' => '14', 'experience' => '5', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Joakim Noah', 'team' => 'Chicago Bulls', 'position' => 'C', 'college' => 'Florida', 'number' => '13', 'experience' => '6', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Lou Amundson', 'team' => 'Chicago Bulls', 'position' => 'PF', 'college' => 'Nevada-Las Vegas', 'number' => '0', 'experience' => '7', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Kris Humphries', 'team' => 'Boston Celtics', 'position' => 'C', 'college' => 'Minnesota', 'number' => '43', 'experience' => '9', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Chris Babb', 'team' => 'Boston Celtics', 'position' => 'SG', 'college' => 'Iowa State', 'number' => '52', 'experience' => '0', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Gerald Wallace', 'team' => 'Boston Celtics', 'position' => 'SF', 'college' => 'Alabama', 'number' => '45', 'experience' => '12', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Kelly Olynyk', 'team' => 'Boston Celtics', 'position' => 'C', 'college' => 'Gonzaga', 'number' => '41', 'experience' => '0', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Rajon Rondo', 'team' => 'Boston Celtics', 'position' => 'PG', 'college' => 'Kentucky', 'number' => '9', 'experience' => '7', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Avery Bradley', 'team' => 'Boston Celtics', 'position' => 'PG', 'college' => 'Texas', 'number' => '0', 'experience' => '3', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Jeff Green', 'team' => 'Boston Celtics', 'position' => 'SF', 'college' => 'Georgetown', 'number' => '8', 'experience' => '5', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Jared Sullinger', 'team' => 'Boston Celtics', 'position' => 'C', 'college' => 'Ohio State', 'number' => '7', 'experience' => '1', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Brandon Bass', 'team' => 'Boston Celtics', 'position' => 'PF', 'college' => 'Louisiana State', 'number' => '30', 'experience' => '8', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Joel Anthony', 'team' => 'Boston Celtics', 'position' => 'C', 'college' => 'UNLV', 'number' => '50', 'experience' => '6', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Keith Bogans', 'team' => 'Boston Celtics', 'position' => 'SG', 'college' => 'Kentucky', 'number' => '4', 'experience' => '10', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Phil Pressey', 'team' => 'Boston Celtics', 'position' => 'PG', 'college' => 'Missouri', 'number' => '26', 'experience' => '0', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Jerryd Bayless', 'team' => 'Boston Celtics', 'position' => 'SG', 'college' => 'Arizona', 'number' => '11', 'experience' => '5', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Cole Aldrich', 'team' => 'New York Knicks', 'position' => 'C', 'college' => 'Kansas', 'number' => '45', 'experience' => '3', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Shannon Brown', 'team' => 'New York Knicks', 'position' => 'SG', 'college' => 'Michigan State', 'number' => '26', 'experience' => '7', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Iman Shumpert', 'team' => 'New York Knicks', 'position' => 'SG', 'college' => 'Georgia Tech', 'number' => '21', 'experience' => '2', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Jeremy Tyler', 'team' => 'New York Knicks', 'position' => 'PF', 'college' => 'San Diego (HS), CA, USA', 'number' => '4', 'experience' => '2', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Carmelo Anthony', 'team' => 'New York Knicks', 'position' => 'SF', 'college' => 'Syracuse', 'number' => '7', 'experience' => '10', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Tim Hardaway Jr.', 'team' => 'New York Knicks', 'position' => 'SG', 'college' => 'Michigan', 'number' => '5', 'experience' => '0', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Tyson Chandler', 'team' => 'New York Knicks', 'position' => 'C', 'college' => 'Dominguez HS (CA)', 'number' => '6', 'experience' => '12', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'J.R. Smith', 'team' => 'New York Knicks', 'position' => 'SG', 'college' => 'St. Benedict\'s Prep HS (NJ)', 'number' => '8', 'experience' => '9', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Amar\'e Stoudemire', 'team' => 'New York Knicks', 'position' => 'PF', 'college' => 'Cypress Creek HS (FL)', 'number' => '1', 'experience' => '11', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Raymond Felton', 'team' => 'New York Knicks', 'position' => 'PG', 'college' => 'North Carolina', 'number' => '2', 'experience' => '8', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Toure\' Murry', 'team' => 'New York Knicks', 'position' => 'SG', 'college' => 'Wichita State', 'number' => '23', 'experience' => '0', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Kenyon Martin', 'team' => 'New York Knicks', 'position' => 'PF', 'college' => 'Cincinnati', 'number' => '3', 'experience' => '13', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Jannero Pargo', 'team' => 'Charlotte Bobcats', 'position' => 'PG', 'college' => 'Arkansas', 'number' => '5', 'experience' => '9', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'D.J. White', 'team' => 'Charlotte Bobcats', 'position' => 'PF', 'college' => 'Indiana', 'number' => '0', 'experience' => '5', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Luke Ridnour', 'team' => 'Charlotte Bobcats', 'position' => 'PG', 'college' => 'Oregon', 'number' => '13', 'experience' => '10', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Anthony Tolliver', 'team' => 'Charlotte Bobcats', 'position' => 'PF', 'college' => 'Creighton', 'number' => '43', 'experience' => '5', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Gerald Henderson', 'team' => 'Charlotte Bobcats', 'position' => 'SG', 'college' => 'Duke', 'number' => '9', 'experience' => '4', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Jeff Taylor', 'team' => 'Charlotte Bobcats', 'position' => 'SF', 'college' => 'Vanderbilt', 'number' => '44', 'experience' => '1', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Josh McRoberts', 'team' => 'Charlotte Bobcats', 'position' => 'PF', 'college' => 'Duke', 'number' => '11', 'experience' => '6', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Gary Neal', 'team' => 'Charlotte Bobcats', 'position' => 'SG', 'college' => 'Towson', 'number' => '12', 'experience' => '3', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Brendan Haywood', 'team' => 'Charlotte Bobcats', 'position' => 'C', 'college' => 'North Carolina', 'number' => '33', 'experience' => '12', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Al Jefferson', 'team' => 'Charlotte Bobcats', 'position' => 'C', 'college' => 'Prentiss HS (MS)', 'number' => '25', 'experience' => '9', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Chris Douglas-Roberts', 'team' => 'Charlotte Bobcats', 'position' => 'SG', 'college' => 'Memphis', 'number' => '55', 'experience' => '4', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Kemba Walker', 'team' => 'Charlotte Bobcats', 'position' => 'PG', 'college' => 'Connecticut', 'number' => '15', 'experience' => '2', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Cody Zeller', 'team' => 'Charlotte Bobcats', 'position' => 'C', 'college' => 'Indiana', 'number' => '40', 'experience' => '0', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Michael Kidd-Gilchrist', 'team' => 'Charlotte Bobcats', 'position' => 'SF', 'college' => 'Kentucky', 'number' => '14', 'experience' => '1', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Glen Rice Jr.', 'team' => 'Washington Wizards', 'position' => 'SG', 'college' => 'Georgia Tech', 'number' => '14', 'experience' => '0', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Drew Gooden', 'team' => 'Washington Wizards', 'position' => 'PF', 'college' => 'Kansas', 'number' => '90', 'experience' => '11', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Chris Singleton', 'team' => 'Washington Wizards', 'position' => 'SF', 'college' => 'Florida State', 'number' => '31', 'experience' => '2', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'John Wall', 'team' => 'Washington Wizards', 'position' => 'PG', 'college' => 'Kentucky', 'number' => '2', 'experience' => '3', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Otto Porter', 'team' => 'Washington Wizards', 'position' => 'SF', 'college' => 'Georgetown', 'number' => '22', 'experience' => '0', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Trevor Booker', 'team' => 'Washington Wizards', 'position' => 'PF', 'college' => 'Clemson', 'number' => '35', 'experience' => '3', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Martell Webster', 'team' => 'Washington Wizards', 'position' => 'SF', 'college' => 'Seattle Prep HS (WA)', 'number' => '9', 'experience' => '8', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Trevor Ariza', 'team' => 'Washington Wizards', 'position' => 'SF', 'college' => 'UCLA', 'number' => '1', 'experience' => '9', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Al Harrington', 'team' => 'Washington Wizards', 'position' => 'PF', 'college' => 'St. Patrick\'s HS (NJ)', 'number' => '7', 'experience' => '15', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Andre Miller', 'team' => 'Washington Wizards', 'position' => 'PG', 'college' => 'Utah', 'number' => '24', 'experience' => '14', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Kevin Seraphin', 'team' => 'Washington Wizards', 'position' => 'C', 'college' => 'Cholet Basket (FRA)', 'number' => '13', 'experience' => '3', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Garrett Temple', 'team' => 'Washington Wizards', 'position' => 'SG', 'college' => 'Louisiana State', 'number' => '17', 'experience' => '3', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Marcin Gortat', 'team' => 'Washington Wizards', 'position' => 'C', 'college' => 'RheinEnergie Cologne', 'number' => '4', 'experience' => '6', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Nene Hilario', 'team' => 'Washington Wizards', 'position' => 'PF', 'college' => 'Vasco de Gama', 'number' => '42', 'experience' => '11', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Bradley Beal', 'team' => 'Washington Wizards', 'position' => 'SG', 'college' => 'Florida', 'number' => '3', 'experience' => '1', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Tim Duncan', 'team' => 'San Antonio Spurs', 'position' => 'PF', 'college' => 'Wake Forest', 'number' => '21', 'experience' => '16', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Danny Green', 'team' => 'San Antonio Spurs', 'position' => 'SG', 'college' => 'North Carolina', 'number' => '4', 'experience' => '4', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Boris Diaw', 'team' => 'San Antonio Spurs', 'position' => 'PF', 'college' => 'Pau Orthez', 'number' => '33', 'experience' => '10', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Cory Joseph', 'team' => 'San Antonio Spurs', 'position' => 'PG', 'college' => 'Texas', 'number' => '5', 'experience' => '2', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Damion James', 'team' => 'San Antonio Spurs', 'position' => 'SF', 'college' => 'Texas', 'number' => '7', 'experience' => '3', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Tiago Splitter', 'team' => 'San Antonio Spurs', 'position' => 'C', 'college' => 'Saski Baskonia', 'number' => '22', 'experience' => '3', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Matt Bonner', 'team' => 'San Antonio Spurs', 'position' => 'PF', 'college' => 'Florida', 'number' => '15', 'experience' => '9', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Austin Daye', 'team' => 'San Antonio Spurs', 'position' => 'SF', 'college' => 'Gonzaga', 'number' => '23', 'experience' => '4', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Manu Ginobili', 'team' => 'San Antonio Spurs', 'position' => 'SG', 'college' => 'Kinder Bologna', 'number' => '20', 'experience' => '11', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Patty Mills', 'team' => 'San Antonio Spurs', 'position' => 'PG', 'college' => 'St. Mary\'s (CA)', 'number' => '8', 'experience' => '4', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Aron Baynes', 'team' => 'San Antonio Spurs', 'position' => 'PF', 'college' => 'Washington State', 'number' => '16', 'experience' => '1', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Kawhi Leonard', 'team' => 'San Antonio Spurs', 'position' => 'SF', 'college' => 'San Diego State', 'number' => '2', 'experience' => '2', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Jeff Ayres', 'team' => 'San Antonio Spurs', 'position' => 'C', 'college' => 'Arizona State', 'number' => '11', 'experience' => '3', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'JaVale McGee', 'team' => 'Denver Nuggets', 'position' => 'C', 'college' => 'Nevada-Reno', 'number' => '34', 'experience' => '5', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Anthony Randolph', 'team' => 'Denver Nuggets', 'position' => 'PF', 'college' => 'Louisiana State', 'number' => '15', 'experience' => '5', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Danilo Gallinari', 'team' => 'Denver Nuggets', 'position' => 'SF', 'college' => 'Olimpia Milano', 'number' => '8', 'experience' => '5', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Nate Robinson', 'team' => 'Denver Nuggets', 'position' => 'PG', 'college' => 'Washington', 'number' => '10', 'experience' => '8', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Kenneth Faried', 'team' => 'Denver Nuggets', 'position' => 'PF', 'college' => 'Morehead State', 'number' => '35', 'experience' => '2', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Randy Foye', 'team' => 'Denver Nuggets', 'position' => 'SG', 'college' => 'Villanova', 'number' => '4', 'experience' => '7', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'J.J. Hickson', 'team' => 'Denver Nuggets', 'position' => 'C', 'college' => 'NC State', 'number' => '7', 'experience' => '5', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Ty Lawson', 'team' => 'Denver Nuggets', 'position' => 'PG', 'college' => 'North Carolina', 'number' => '3', 'experience' => '4', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Evan Fournier', 'team' => 'Denver Nuggets', 'position' => 'SG', 'college' => 'France', 'number' => '94', 'experience' => '1', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Aaron Brooks', 'team' => 'Denver Nuggets', 'position' => 'PG', 'college' => 'Oregon', 'number' => '0', 'experience' => '5', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Darrell Arthur', 'team' => 'Denver Nuggets', 'position' => 'PF', 'college' => 'Kansas', 'number' => '0', 'experience' => '5', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Wilson Chandler', 'team' => 'Denver Nuggets', 'position' => 'SF', 'college' => 'DePaul', 'number' => '21', 'experience' => '6', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Quincy Miller', 'team' => 'Denver Nuggets', 'position' => 'SF', 'college' => 'Baylor', 'number' => '30', 'experience' => '1', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Jan Vesely', 'team' => 'Denver Nuggets', 'position' => 'PF', 'college' => 'Partizan Belgrade', 'number' => '24', 'experience' => '2', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Festus Ezeli', 'team' => 'Golden State Warriors', 'position' => 'C', 'college' => 'Vanderbilt', 'number' => '31', 'experience' => '1', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Jordan Crawford', 'team' => 'Golden State Warriors', 'position' => 'SG', 'college' => 'Xavier', 'number' => '55', 'experience' => '3', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Andrew Bogut', 'team' => 'Golden State Warriors', 'position' => 'C', 'college' => 'Utah', 'number' => '12', 'experience' => '8', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Klay Thompson', 'team' => 'Golden State Warriors', 'position' => 'SG', 'college' => 'Washington State', 'number' => '11', 'experience' => '2', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Draymond Green', 'team' => 'Golden State Warriors', 'position' => 'SF', 'college' => 'Michigan State', 'number' => '23', 'experience' => '1', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Jermaine O\'Neal', 'team' => 'Golden State Warriors', 'position' => 'C', 'college' => 'Eau Claire HS (SC)', 'number' => '7', 'experience' => '17', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Stephen Curry', 'team' => 'Golden State Warriors', 'position' => 'PG', 'college' => 'Davidson', 'number' => '30', 'experience' => '4', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Hilton Armstrong', 'team' => 'Golden State Warriors', 'position' => 'PF', 'college' => 'Connecticut', 'number' => '57', 'experience' => '5', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'David Lee', 'team' => 'Golden State Warriors', 'position' => 'PF', 'college' => 'Florida', 'number' => '10', 'experience' => '8', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Andre Iguodala', 'team' => 'Golden State Warriors', 'position' => 'SF', 'college' => 'Arizona', 'number' => '9', 'experience' => '9', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Steve Blake', 'team' => 'Golden State Warriors', 'position' => 'PG', 'college' => 'Maryland', 'number' => '25', 'experience' => '10', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Harrison Barnes', 'team' => 'Golden State Warriors', 'position' => 'SF', 'college' => 'North Carolina', 'number' => '40', 'experience' => '1', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Marreese Speights', 'team' => 'Golden State Warriors', 'position' => 'PF', 'college' => 'Florida', 'number' => '5', 'experience' => '5', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Ben McLemore', 'team' => 'Sacramento Kings', 'position' => 'SG', 'college' => 'Kansas', 'number' => '16', 'experience' => '0', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Jason Thompson', 'team' => 'Sacramento Kings', 'position' => 'PF', 'college' => 'Rider', 'number' => '34', 'experience' => '5', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Aaron Gray', 'team' => 'Sacramento Kings', 'position' => 'C', 'college' => 'Pittsburgh', 'number' => '33', 'experience' => '6', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Jared Cunningham', 'team' => 'Sacramento Kings', 'position' => 'SG', 'college' => 'Oregon State', 'number' => '9', 'experience' => '1', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Rudy Gay', 'team' => 'Sacramento Kings', 'position' => 'SF', 'college' => 'Connecticut', 'number' => '8', 'experience' => '7', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Travis Outlaw', 'team' => 'Sacramento Kings', 'position' => 'SF', 'college' => 'Starkville HS (MS)', 'number' => '25', 'experience' => '10', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Jason Terry', 'team' => 'Sacramento Kings', 'position' => 'SG', 'college' => 'Arizona', 'number' => '31', 'experience' => '14', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Reggie Evans', 'team' => 'Sacramento Kings', 'position' => 'PF', 'college' => 'Iowa', 'number' => '30', 'experience' => '11', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Derrick Williams', 'team' => 'Sacramento Kings', 'position' => 'PF', 'college' => 'Arizona', 'number' => '13', 'experience' => '2', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Ray McCallum Jr.', 'team' => 'Sacramento Kings', 'position' => 'PG', 'college' => 'Detroit', 'number' => '3', 'experience' => '0', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Willie Reed', 'team' => 'Sacramento Kings', 'position' => 'PF', 'college' => 'St. Louis', 'number' => '3', 'experience' => '0', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Carl Landry', 'team' => 'Sacramento Kings', 'position' => 'PF', 'college' => 'Purdue', 'number' => '24', 'experience' => '6', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Isaiah Thomas', 'team' => 'Sacramento Kings', 'position' => 'PG', 'college' => 'Washington', 'number' => '22', 'experience' => '2', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Quincy Acy', 'team' => 'Sacramento Kings', 'position' => 'SF', 'college' => 'Baylor', 'number' => '5', 'experience' => '1', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'DeMarcus Cousins', 'team' => 'Sacramento Kings', 'position' => 'C', 'college' => 'Kentucky', 'number' => '15', 'experience' => '3', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'James Jones', 'team' => 'Miami Heat', 'position' => 'SF', 'college' => 'Miami', 'number' => '22', 'experience' => '10', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'LeBron James', 'team' => 'Miami Heat', 'position' => 'SF', 'college' => 'St. Vincent-St. Mary HS (OH)', 'number' => '6', 'experience' => '10', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Dwyane Wade', 'team' => 'Miami Heat', 'position' => 'SG', 'college' => 'Marquette', 'number' => '3', 'experience' => '10', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Greg Oden', 'team' => 'Miami Heat', 'position' => 'C', 'college' => 'Ohio State', 'number' => '20', 'experience' => '2', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Ray Allen', 'team' => 'Miami Heat', 'position' => 'SG', 'college' => 'Connecticut', 'number' => '34', 'experience' => '17', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Chris Andersen', 'team' => 'Miami Heat', 'position' => 'PF', 'college' => 'Blinn Junior College', 'number' => '11', 'experience' => '11', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Toney Douglas', 'team' => 'Miami Heat', 'position' => 'PG', 'college' => 'Florida State', 'number' => '0', 'experience' => '4', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Rashard Lewis', 'team' => 'Miami Heat', 'position' => 'PF', 'college' => 'Alief Elsik HS (TX)', 'number' => '9', 'experience' => '15', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Michael Beasley', 'team' => 'Miami Heat', 'position' => 'SF', 'college' => 'Kansas State', 'number' => '8', 'experience' => '5', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Mario Chalmers', 'team' => 'Miami Heat', 'position' => 'PG', 'college' => 'Kansas', 'number' => '15', 'experience' => '5', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Justin Hamilton', 'team' => 'Miami Heat', 'position' => 'C', 'college' => 'LSU', 'number' => '7', 'experience' => '0', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Shane Battier', 'team' => 'Miami Heat', 'position' => 'SF', 'college' => 'Duke', 'number' => '31', 'experience' => '12', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Udonis Haslem', 'team' => 'Miami Heat', 'position' => 'PF', 'college' => 'Florida', 'number' => '40', 'experience' => '10', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Norris Cole', 'team' => 'Miami Heat', 'position' => 'PG', 'college' => 'Cleveland State', 'number' => '30', 'experience' => '2', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Chris Bosh', 'team' => 'Miami Heat', 'position' => 'C', 'college' => 'Georgia Tech', 'number' => '1', 'experience' => '10', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Doron Lamb', 'team' => 'Orlando Magic', 'position' => 'SG', 'college' => 'Kentucky', 'number' => '1', 'experience' => '1', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Ronnie Price', 'team' => 'Orlando Magic', 'position' => 'PG', 'college' => 'Utah Valley', 'number' => '10', 'experience' => '8', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Jason Maxiell', 'team' => 'Orlando Magic', 'position' => 'PF', 'college' => 'Cincinnati', 'number' => '54', 'experience' => '8', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Arron Afflalo', 'team' => 'Orlando Magic', 'position' => 'SG', 'college' => 'UCLA', 'number' => '4', 'experience' => '6', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'E\'Twaun Moore', 'team' => 'Orlando Magic', 'position' => 'PG', 'college' => 'Purdue', 'number' => '55', 'experience' => '2', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Jameer Nelson', 'team' => 'Orlando Magic', 'position' => 'PG', 'college' => 'Saint Joseph\'s', 'number' => '14', 'experience' => '9', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Nikola Vucevic', 'team' => 'Orlando Magic', 'position' => 'C', 'college' => 'USC', 'number' => '9', 'experience' => '2', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Tobias Harris', 'team' => 'Orlando Magic', 'position' => 'SF', 'college' => 'Tennessee', 'number' => '12', 'experience' => '2', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Andrew Nicholson', 'team' => 'Orlando Magic', 'position' => 'PF', 'college' => 'St. Bonaventure', 'number' => '44', 'experience' => '1', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Victor Oladipo', 'team' => 'Orlando Magic', 'position' => 'SG', 'college' => 'Indiana', 'number' => '5', 'experience' => '0', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Dewayne Dedmon', 'team' => 'Orlando Magic', 'position' => 'C', 'college' => 'USC', 'number' => '3', 'experience' => '0', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Moe Harkless', 'team' => 'Orlando Magic', 'position' => 'SF', 'college' => 'St. John\'s (N.Y.)', 'number' => '21', 'experience' => '1', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Kyle O\'Quinn', 'team' => 'Orlando Magic', 'position' => 'PF', 'college' => 'Norfolk State', 'number' => '2', 'experience' => '1', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Louis Williams', 'team' => 'Atlanta Hawks', 'position' => 'SG', 'college' => 'South Gwinnett HS (GA)', 'number' => '3', 'experience' => '8', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Elton Brand', 'team' => 'Atlanta Hawks', 'position' => 'PF', 'college' => 'Duke', 'number' => '42', 'experience' => '14', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Cartier Martin', 'team' => 'Atlanta Hawks', 'position' => 'SF', 'college' => 'Kansas State', 'number' => '20', 'experience' => '5', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Paul Millsap', 'team' => 'Atlanta Hawks', 'position' => 'PF', 'college' => 'Louisiana Tech', 'number' => '4', 'experience' => '7', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'DeMarre Carroll', 'team' => 'Atlanta Hawks', 'position' => 'SF', 'college' => 'Missouri', 'number' => '5', 'experience' => '4', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Mike Muscala', 'team' => 'Atlanta Hawks', 'position' => 'PF', 'college' => 'Bucknell', 'number' => '31', 'experience' => '0', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Jeff Teague', 'team' => 'Atlanta Hawks', 'position' => 'PG', 'college' => 'Wake Forest', 'number' => '0', 'experience' => '4', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Kyle Korver', 'team' => 'Atlanta Hawks', 'position' => 'SG', 'college' => 'Creighton', 'number' => '26', 'experience' => '10', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Al Horford', 'team' => 'Atlanta Hawks', 'position' => 'C', 'college' => 'Florida', 'number' => '15', 'experience' => '6', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Mike Scott', 'team' => 'Atlanta Hawks', 'position' => 'PF', 'college' => 'Virginia', 'number' => '32', 'experience' => '1', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Shelvin Mack', 'team' => 'Atlanta Hawks', 'position' => 'PG', 'college' => 'Butler', 'number' => '8', 'experience' => '2', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'John Jenkins', 'team' => 'Atlanta Hawks', 'position' => 'SG', 'college' => 'Vanderbilt', 'number' => '12', 'experience' => '1', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Tony Wroten', 'team' => 'Philadelphia 76ers', 'position' => 'SG', 'college' => 'Washington', 'number' => '8', 'experience' => '1', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Michael Carter-Williams', 'team' => 'Philadelphia 76ers', 'position' => 'PG', 'college' => 'Syracuse', 'number' => '1', 'experience' => '0', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Nerlens Noel', 'team' => 'Philadelphia 76ers', 'position' => 'C', 'college' => 'Kentucky', 'number' => '4', 'experience' => '0', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Brandon Davies', 'team' => 'Philadelphia 76ers', 'position' => 'PF', 'college' => 'Brigham Young', 'number' => '20', 'experience' => '0', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'James Anderson', 'team' => 'Philadelphia 76ers', 'position' => 'SG', 'college' => 'Oklahoma State', 'number' => '9', 'experience' => '3', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Adonis Thomas', 'team' => 'Philadelphia 76ers', 'position' => 'SG', 'college' => 'Memphis', 'number' => '8', 'experience' => '0', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Henry Sims', 'team' => 'Philadelphia 76ers', 'position' => 'C', 'college' => 'Georgetown', 'number' => '35', 'experience' => '1', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Thaddeus Young', 'team' => 'Philadelphia 76ers', 'position' => 'PF', 'college' => 'Georgia Tech', 'number' => '21', 'experience' => '6', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Arnett Moultrie', 'team' => 'Philadelphia 76ers', 'position' => 'PF', 'college' => 'Mississippi State', 'number' => '5', 'experience' => '1', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Elliot Williams', 'team' => 'Philadelphia 76ers', 'position' => 'SG', 'college' => 'Memphis', 'number' => '25', 'experience' => '3', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Jason Richardson', 'team' => 'Philadelphia 76ers', 'position' => 'SG', 'college' => 'Michigan State', 'number' => '23', 'experience' => '12', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Byron Mullens', 'team' => 'Philadelphia 76ers', 'position' => 'C', 'college' => 'Ohio State', 'number' => '30', 'experience' => '4', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Hollis Thompson', 'team' => 'Philadelphia 76ers', 'position' => 'SG', 'college' => 'Georgetown', 'number' => '31', 'experience' => '0', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Jarvis Varnado', 'team' => 'Philadelphia 76ers', 'position' => 'PF', 'college' => 'Mississippi State', 'number' => '40', 'experience' => '1', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Rasual Butler', 'team' => 'Indiana Pacers', 'position' => 'SG', 'college' => 'La Salle', 'number' => '8', 'experience' => '10', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Lance Stephenson', 'team' => 'Indiana Pacers', 'position' => 'SG', 'college' => 'Cincinnati', 'number' => '1', 'experience' => '3', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Donald Sloan', 'team' => 'Indiana Pacers', 'position' => 'PG', 'college' => 'Texas A&M', 'number' => '15', 'experience' => '2', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Roy Hibbert', 'team' => 'Indiana Pacers', 'position' => 'C', 'college' => 'Georgetown', 'number' => '55', 'experience' => '5', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'David West', 'team' => 'Indiana Pacers', 'position' => 'PF', 'college' => 'Xavier (Ohio)', 'number' => '21', 'experience' => '10', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Lavoy Allen', 'team' => 'Indiana Pacers', 'position' => 'PF', 'college' => 'Temple', 'number' => '5', 'experience' => '2', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Andrew Bynum', 'team' => 'Indiana Pacers', 'position' => 'C', 'college' => 'St. Joseph HS (NJ)', 'number' => '17', 'experience' => '7', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Luis Scola', 'team' => 'Indiana Pacers', 'position' => 'PF', 'college' => 'Tau Ceramica (Argentina)', 'number' => '4', 'experience' => '6', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Chris Copeland', 'team' => 'Indiana Pacers', 'position' => 'SF', 'college' => 'Colorado', 'number' => '22', 'experience' => '1', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'George Hill', 'team' => 'Indiana Pacers', 'position' => 'PG', 'college' => 'IUPUI', 'number' => '3', 'experience' => '5', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'C.J. Watson', 'team' => 'Indiana Pacers', 'position' => 'PG', 'college' => 'Tennessee', 'number' => '32', 'experience' => '6', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Evan Turner', 'team' => 'Indiana Pacers', 'position' => 'SF', 'college' => 'Ohio State', 'number' => '12', 'experience' => '3', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Paul George', 'team' => 'Indiana Pacers', 'position' => 'SF', 'college' => 'Fresno State', 'number' => '24', 'experience' => '3', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Solomon Hill', 'team' => 'Indiana Pacers', 'position' => 'SF', 'college' => 'Arizona', 'number' => '9', 'experience' => '0', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'O.J. Mayo', 'team' => 'Milwaukee Bucks', 'position' => 'SG', 'college' => 'USC', 'number' => '0', 'experience' => '5', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Khris Middleton', 'team' => 'Milwaukee Bucks', 'position' => 'PF', 'college' => 'Texas A&M', 'number' => '22', 'experience' => '1', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Chris Wright', 'team' => 'Milwaukee Bucks', 'position' => 'SF', 'college' => 'Dayton', 'number' => '15', 'experience' => '1', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Nate Wolters', 'team' => 'Milwaukee Bucks', 'position' => 'PG', 'college' => 'South Dakota State', 'number' => '6', 'experience' => '0', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Ramon Sessions', 'team' => 'Milwaukee Bucks', 'position' => 'PG', 'college' => 'Nevada', 'number' => '13', 'experience' => '6', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Carlos Delfino', 'team' => 'Milwaukee Bucks', 'position' => 'SG', 'college' => 'Skipper Bologna', 'number' => '10', 'experience' => '8', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Ekpe Udoh', 'team' => 'Milwaukee Bucks', 'position' => 'PF', 'college' => 'Baylor', 'number' => '5', 'experience' => '3', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Jeff Adrien', 'team' => 'Milwaukee Bucks', 'position' => 'PF', 'college' => 'Connecticut', 'number' => '12', 'experience' => '3', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'John Henson', 'team' => 'Milwaukee Bucks', 'position' => 'C', 'college' => 'North Carolina', 'number' => '31', 'experience' => '1', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Brandon Knight', 'team' => 'Milwaukee Bucks', 'position' => 'SG', 'college' => 'Kentucky', 'number' => '11', 'experience' => '2', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Larry Sanders', 'team' => 'Milwaukee Bucks', 'position' => 'C', 'college' => 'Virginia Commonwealth', 'number' => '8', 'experience' => '3', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Landry Fields', 'team' => 'Toronto Raptors', 'position' => 'SF', 'college' => 'Stanford', 'number' => '2', 'experience' => '3', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Dwight Buycks', 'team' => 'Toronto Raptors', 'position' => 'PG', 'college' => 'Marquette', 'number' => '13', 'experience' => '0', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Julyan Stone', 'team' => 'Toronto Raptors', 'position' => 'SG', 'college' => 'Texas-El Paso', 'number' => '77', 'experience' => '2', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Patrick Patterson', 'team' => 'Toronto Raptors', 'position' => 'PF', 'college' => 'Kentucky', 'number' => '54', 'experience' => '3', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'DeMar DeRozan', 'team' => 'Toronto Raptors', 'position' => 'SG', 'college' => 'USC', 'number' => '10', 'experience' => '4', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Tyler Hansbrough', 'team' => 'Toronto Raptors', 'position' => 'PF', 'college' => 'North Carolina', 'number' => '50', 'experience' => '4', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Kyle Lowry', 'team' => 'Toronto Raptors', 'position' => 'PG', 'college' => 'Villanova', 'number' => '7', 'experience' => '7', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Amir Johnson', 'team' => 'Toronto Raptors', 'position' => 'PF', 'college' => 'Westchester HS (CA)', 'number' => '15', 'experience' => '8', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Terrence Ross', 'team' => 'Toronto Raptors', 'position' => 'SG', 'college' => 'Washington', 'number' => '31', 'experience' => '1', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Steve Novak', 'team' => 'Toronto Raptors', 'position' => 'SF', 'college' => 'Marquette', 'number' => '16', 'experience' => '7', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Greivis Vasquez', 'team' => 'Toronto Raptors', 'position' => 'PG', 'college' => 'Maryland', 'number' => '21', 'experience' => '3', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Chuck Hayes', 'team' => 'Toronto Raptors', 'position' => 'PF', 'college' => 'Kentucky', 'number' => '44', 'experience' => '8', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Nando De Colo', 'team' => 'Toronto Raptors', 'position' => 'PG', 'college' => 'Saint Catherine (France)', 'number' => '3', 'experience' => '1', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'John Salmons', 'team' => 'Toronto Raptors', 'position' => 'SF', 'college' => 'Miami (Fla.)', 'number' => '25', 'experience' => '11', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Andrei Kirilenko', 'team' => 'Brooklyn Nets', 'position' => 'SF', 'college' => 'St. Petersburg (Russia)', 'number' => '47', 'experience' => '11', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Marquis Teague', 'team' => 'Brooklyn Nets', 'position' => 'PG', 'college' => 'Kentucky', 'number' => '12', 'experience' => '1', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Alan Anderson', 'team' => 'Brooklyn Nets', 'position' => 'SF', 'college' => 'Michigan State', 'number' => '6', 'experience' => '4', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Joe Johnson', 'team' => 'Brooklyn Nets', 'position' => 'SG', 'college' => 'Arkansas', 'number' => '7', 'experience' => '12', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Paul Pierce', 'team' => 'Brooklyn Nets', 'position' => 'SF', 'college' => 'Kansas', 'number' => '34', 'experience' => '15', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Jorge Gutierrez', 'team' => 'Brooklyn Nets', 'position' => 'PG', 'college' => 'California', 'number' => '13', 'experience' => '0', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Andray Blatche', 'team' => 'Brooklyn Nets', 'position' => 'C', 'college' => 'South Kent Prep HS (CT)', 'number' => '0', 'experience' => '8', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Shaun Livingston', 'team' => 'Brooklyn Nets', 'position' => 'PG', 'college' => 'Peoria Central HS (IL)', 'number' => '14', 'experience' => '8', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Kevin Garnett', 'team' => 'Brooklyn Nets', 'position' => 'PF', 'college' => 'Farragut Academy HS (IL)', 'number' => '2', 'experience' => '18', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Deron Williams', 'team' => 'Brooklyn Nets', 'position' => 'PG', 'college' => 'Illinois', 'number' => '8', 'experience' => '8', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Mason Plumlee', 'team' => 'Brooklyn Nets', 'position' => 'PF', 'college' => 'Duke', 'number' => '1', 'experience' => '0', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Jason Collins', 'team' => 'Brooklyn Nets', 'position' => 'C', 'college' => 'Stanford', 'number' => '98', 'experience' => '12', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Brook Lopez', 'team' => 'Brooklyn Nets', 'position' => 'C', 'college' => 'Stanford', 'number' => '11', 'experience' => '5', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Marcus Thornton', 'team' => 'Brooklyn Nets', 'position' => 'SG', 'college' => 'Louisiana State', 'number' => '10', 'experience' => '4', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Carrick Felix', 'team' => 'Cleveland Cavaliers', 'position' => 'SG', 'college' => 'Arizona State', 'number' => '30', 'experience' => '0', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Dion Waiters', 'team' => 'Cleveland Cavaliers', 'position' => 'SG', 'college' => 'Syracuse', 'number' => '3', 'experience' => '1', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Tristan Thompson', 'team' => 'Cleveland Cavaliers', 'position' => 'PF', 'college' => 'Texas', 'number' => '13', 'experience' => '2', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Luol Deng', 'team' => 'Cleveland Cavaliers', 'position' => 'SF', 'college' => 'Duke', 'number' => '9', 'experience' => '9', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'C.J. Miles', 'team' => 'Cleveland Cavaliers', 'position' => 'SG', 'college' => 'Skyline HS (TX)', 'number' => '0', 'experience' => '8', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Anthony Bennett', 'team' => 'Cleveland Cavaliers', 'position' => 'SF', 'college' => 'UNLV', 'number' => '15', 'experience' => '0', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Jarrett Jack', 'team' => 'Cleveland Cavaliers', 'position' => 'PG', 'college' => 'Georgia Tech', 'number' => '1', 'experience' => '8', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Tyler Zeller', 'team' => 'Cleveland Cavaliers', 'position' => 'C', 'college' => 'North Carolina', 'number' => '40', 'experience' => '1', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Kyrie Irving', 'team' => 'Cleveland Cavaliers', 'position' => 'PG', 'college' => 'Duke', 'number' => '2', 'experience' => '2', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Spencer Hawes', 'team' => 'Cleveland Cavaliers', 'position' => 'C', 'college' => 'Washington', 'number' => '32', 'experience' => '6', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Alonzo Gee', 'team' => 'Cleveland Cavaliers', 'position' => 'SF', 'college' => 'Alabama', 'number' => '33', 'experience' => '4', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Matthew Dellavedova', 'team' => 'Cleveland Cavaliers', 'position' => 'SG', 'college' => 'St. Mary\'s (CA)', 'number' => '8', 'experience' => '0', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Scotty Hopson', 'team' => 'Cleveland Cavaliers', 'position' => 'SG', 'college' => 'Tennessee', 'number' => '24', 'experience' => '0', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Peyton Siva', 'team' => 'Detroit Pistons', 'position' => 'PG', 'college' => 'Louisville', 'number' => '34', 'experience' => '0', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Chauncey Billups', 'team' => 'Detroit Pistons', 'position' => 'SG', 'college' => 'Colorado', 'number' => '1', 'experience' => '16', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Andre Drummond', 'team' => 'Detroit Pistons', 'position' => 'C', 'college' => 'Connecticut', 'number' => '0', 'experience' => '1', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Charlie Villanueva', 'team' => 'Detroit Pistons', 'position' => 'PF', 'college' => 'Connecticut', 'number' => '31', 'experience' => '8', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Will Bynum', 'team' => 'Detroit Pistons', 'position' => 'PG', 'college' => 'Georgia Tech', 'number' => '12', 'experience' => '6', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Greg Monroe', 'team' => 'Detroit Pistons', 'position' => 'PF', 'college' => 'Georgetown', 'number' => '10', 'experience' => '3', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Josh Smith', 'team' => 'Detroit Pistons', 'position' => 'PF', 'college' => 'Oak Hill Academy (VA)', 'number' => '6', 'experience' => '9', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Rodney Stuckey', 'team' => 'Detroit Pistons', 'position' => 'SG', 'college' => 'Eastern Washington', 'number' => '3', 'experience' => '6', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Brandon Jennings', 'team' => 'Detroit Pistons', 'position' => 'PG', 'college' => 'Oak Hill Academy (VA)', 'number' => '7', 'experience' => '4', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Tony Mitchell', 'team' => 'Detroit Pistons', 'position' => 'PF', 'college' => 'North Texas', 'number' => '9', 'experience' => '0', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Kentavious Caldwell-Pope', 'team' => 'Detroit Pistons', 'position' => 'SG', 'college' => 'Georgia', 'number' => '5', 'experience' => '0', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Kyle Singler', 'team' => 'Detroit Pistons', 'position' => 'SF', 'college' => 'Duke', 'number' => '25', 'experience' => '1', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Josh Harrellson', 'team' => 'Detroit Pistons', 'position' => 'PF', 'college' => 'Kentucky', 'number' => '55', 'experience' => '2', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Steve Nash', 'team' => 'Los Angeles Lakers', 'position' => 'PG', 'college' => 'Santa Clara', 'number' => '10', 'experience' => '17', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Robert Sacre', 'team' => 'Los Angeles Lakers', 'position' => 'C', 'college' => 'Gonzaga', 'number' => '50', 'experience' => '1', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Wesley Johnson', 'team' => 'Los Angeles Lakers', 'position' => 'SF', 'college' => 'Syracuse', 'number' => '11', 'experience' => '3', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Ryan Kelly', 'team' => 'Los Angeles Lakers', 'position' => 'PF', 'college' => 'Duke', 'number' => '4', 'experience' => '0', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Kent Bazemore', 'team' => 'Los Angeles Lakers', 'position' => 'SG', 'college' => 'Old Dominion', 'number' => '6', 'experience' => '1', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Jordan Farmar', 'team' => 'Los Angeles Lakers', 'position' => 'PG', 'college' => 'UCLA', 'number' => '1', 'experience' => '6', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Chris Kaman', 'team' => 'Los Angeles Lakers', 'position' => 'C', 'college' => 'Central Michigan', 'number' => '9', 'experience' => '10', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Jordan Hill', 'team' => 'Los Angeles Lakers', 'position' => 'PF', 'college' => 'Arizona', 'number' => '27', 'experience' => '4', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'MarShon Brooks', 'team' => 'Los Angeles Lakers', 'position' => 'SG', 'college' => 'Providence', 'number' => '2', 'experience' => '2', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Kendall Marshall', 'team' => 'Los Angeles Lakers', 'position' => 'PG', 'college' => 'North Carolina', 'number' => '12', 'experience' => '1', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Nick Young', 'team' => 'Los Angeles Lakers', 'position' => 'SG', 'college' => 'USC', 'number' => '0', 'experience' => '6', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Jodie Meeks', 'team' => 'Los Angeles Lakers', 'position' => 'SG', 'college' => 'Kentucky', 'number' => '20', 'experience' => '4', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Xavier Henry', 'team' => 'Los Angeles Lakers', 'position' => 'SF', 'college' => 'Kansas', 'number' => '7', 'experience' => '3', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Kobe Bryant', 'team' => 'Los Angeles Lakers', 'position' => 'SG', 'college' => 'Lower Merion HS (PA)', 'number' => '24', 'experience' => '17', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Monta Ellis', 'team' => 'Dallas Mavericks', 'position' => 'SG', 'college' => 'Lanier HS (MS)', 'number' => '11', 'experience' => '8', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Devin Harris', 'team' => 'Dallas Mavericks', 'position' => 'PG', 'college' => 'Wisconsin', 'number' => '20', 'experience' => '9', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Wayne Ellington', 'team' => 'Dallas Mavericks', 'position' => 'SG', 'college' => 'North Carolina', 'number' => '21', 'experience' => '4', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Bernard James', 'team' => 'Dallas Mavericks', 'position' => 'C', 'college' => 'Florida State', 'number' => '5', 'experience' => '1', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Shane Larkin', 'team' => 'Dallas Mavericks', 'position' => 'PG', 'college' => 'Miami (FL)', 'number' => '3', 'experience' => '0', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'DeJuan Blair', 'team' => 'Dallas Mavericks', 'position' => 'C', 'college' => 'Pittsburgh', 'number' => '45', 'experience' => '4', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Ricky Ledo', 'team' => 'Dallas Mavericks', 'position' => 'SG', 'college' => 'Providence', 'number' => '7', 'experience' => '0', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Dirk Nowitzki', 'team' => 'Dallas Mavericks', 'position' => 'PF', 'college' => 'DJK Wurzburg', 'number' => '41', 'experience' => '15', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Brandan Wright', 'team' => 'Dallas Mavericks', 'position' => 'PF', 'college' => 'North Carolina', 'number' => '34', 'experience' => '5', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Samuel Dalembert', 'team' => 'Dallas Mavericks', 'position' => 'C', 'college' => 'Seton Hall', 'number' => '1', 'experience' => '11', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Jae Crowder', 'team' => 'Dallas Mavericks', 'position' => 'SF', 'college' => 'Marquette', 'number' => '9', 'experience' => '1', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Gal Mekel', 'team' => 'Dallas Mavericks', 'position' => 'PG', 'college' => 'Wichita State', 'number' => '33', 'experience' => '0', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Shawn Marion', 'team' => 'Dallas Mavericks', 'position' => 'SF', 'college' => 'UNLV', 'number' => '0', 'experience' => '14', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Vince Carter', 'team' => 'Dallas Mavericks', 'position' => 'SG', 'college' => 'North Carolina', 'number' => '25', 'experience' => '15', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Serge Ibaka', 'team' => 'Oklahoma City Thunder', 'position' => 'PF', 'college' => 'Ricoh Manresa', 'number' => '9', 'experience' => '4', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Derek Fisher', 'team' => 'Oklahoma City Thunder', 'position' => 'PG', 'college' => 'Arkansas-Little Rock', 'number' => '6', 'experience' => '17', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Perry Jones', 'team' => 'Oklahoma City Thunder', 'position' => 'SF', 'college' => 'Baylor', 'number' => '3', 'experience' => '1', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Kevin Durant', 'team' => 'Oklahoma City Thunder', 'position' => 'SF', 'college' => 'Texas', 'number' => '35', 'experience' => '6', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Andre Roberson', 'team' => 'Oklahoma City Thunder', 'position' => 'SF', 'college' => 'Colorado', 'number' => '21', 'experience' => '0', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Russell Westbrook', 'team' => 'Oklahoma City Thunder', 'position' => 'PG', 'college' => 'UCLA', 'number' => '0', 'experience' => '5', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Reggie Jackson', 'team' => 'Oklahoma City Thunder', 'position' => 'PG', 'college' => 'Boston College', 'number' => '15', 'experience' => '2', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Hasheem Thabeet', 'team' => 'Oklahoma City Thunder', 'position' => 'C', 'college' => 'Connecticut', 'number' => '34', 'experience' => '4', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Kendrick Perkins', 'team' => 'Oklahoma City Thunder', 'position' => 'C', 'college' => 'Clifton J. Ozen HS', 'number' => '5', 'experience' => '10', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Jeremy Lamb', 'team' => 'Oklahoma City Thunder', 'position' => 'SG', 'college' => 'Connecticut', 'number' => '11', 'experience' => '1', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Caron Butler', 'team' => 'Oklahoma City Thunder', 'position' => 'SF', 'college' => 'Connecticut', 'number' => '2', 'experience' => '11', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Steven Adams', 'team' => 'Oklahoma City Thunder', 'position' => 'C', 'college' => 'Pittsburgh', 'number' => '12', 'experience' => '0', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Thabo Sefolosha', 'team' => 'Oklahoma City Thunder', 'position' => 'SG', 'college' => 'Angelico Biella', 'number' => '25', 'experience' => '7', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Grant Jerrett', 'team' => 'Oklahoma City Thunder', 'position' => 'PF', 'college' => 'Arizona', 'number' => '47', 'experience' => '0', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Nick Collison', 'team' => 'Oklahoma City Thunder', 'position' => 'PF', 'college' => 'Kansas', 'number' => '4', 'experience' => '9', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Thomas Robinson', 'team' => 'Portland Trail Blazers', 'position' => 'PF', 'college' => 'Kansas', 'number' => '41', 'experience' => '1', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'LaMarcus Aldridge', 'team' => 'Portland Trail Blazers', 'position' => 'PF', 'college' => 'Texas', 'number' => '12', 'experience' => '7', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Meyers Leonard', 'team' => 'Portland Trail Blazers', 'position' => 'C', 'college' => 'Illinois', 'number' => '11', 'experience' => '1', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Damian Lillard', 'team' => 'Portland Trail Blazers', 'position' => 'PG', 'college' => 'Weber State', 'number' => '0', 'experience' => '1', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Allen Crabbe', 'team' => 'Portland Trail Blazers', 'position' => 'SG', 'college' => 'California', 'number' => '23', 'experience' => '0', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Wesley Matthews', 'team' => 'Portland Trail Blazers', 'position' => 'SG', 'college' => 'Marquette', 'number' => '2', 'experience' => '4', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Will Barton', 'team' => 'Portland Trail Blazers', 'position' => 'SG', 'college' => 'Memphis', 'number' => '5', 'experience' => '1', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Earl Watson', 'team' => 'Portland Trail Blazers', 'position' => 'PG', 'college' => 'UCLA', 'number' => '17', 'experience' => '12', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'C.J. McCollum', 'team' => 'Portland Trail Blazers', 'position' => 'SG', 'college' => 'Lehigh', 'number' => '3', 'experience' => '0', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Joel Freeland', 'team' => 'Portland Trail Blazers', 'position' => 'C', 'college' => 'Farnborough College, England', 'number' => '19', 'experience' => '1', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Dorell Wright', 'team' => 'Portland Trail Blazers', 'position' => 'SF', 'college' => 'South Kent Prep HS (CT)', 'number' => '1', 'experience' => '9', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Mo Williams', 'team' => 'Portland Trail Blazers', 'position' => 'PG', 'college' => 'Alabama', 'number' => '25', 'experience' => '10', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Robin Lopez', 'team' => 'Portland Trail Blazers', 'position' => 'C', 'college' => 'Stanford', 'number' => '42', 'experience' => '5', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Anthony Morrow', 'team' => 'New Orleans Pelicans', 'position' => 'SG', 'college' => 'Georgia Tech', 'number' => '3', 'experience' => '5', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Austin Rivers', 'team' => 'New Orleans Pelicans', 'position' => 'SG', 'college' => 'Duke', 'number' => '25', 'experience' => '1', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Ryan Anderson', 'team' => 'New Orleans Pelicans', 'position' => 'PF', 'college' => 'California', 'number' => '33', 'experience' => '5', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Al-Farouq Aminu', 'team' => 'New Orleans Pelicans', 'position' => 'SF', 'college' => 'Wake Forest', 'number' => '0', 'experience' => '3', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Jrue Holiday', 'team' => 'New Orleans Pelicans', 'position' => 'PG', 'college' => 'UCLA', 'number' => '11', 'experience' => '4', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Jeff Withey', 'team' => 'New Orleans Pelicans', 'position' => 'C', 'college' => 'Kansas', 'number' => '5', 'experience' => '0', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Jason Smith', 'team' => 'New Orleans Pelicans', 'position' => 'C', 'college' => 'Colorado State', 'number' => '14', 'experience' => '5', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Luke Babbitt', 'team' => 'New Orleans Pelicans', 'position' => 'SF', 'college' => 'Nevada-Reno', 'number' => '8', 'experience' => '3', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Anthony Davis', 'team' => 'New Orleans Pelicans', 'position' => 'PF', 'college' => 'Kentucky', 'number' => '23', 'experience' => '1', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Brian Roberts', 'team' => 'New Orleans Pelicans', 'position' => 'PG', 'college' => 'Dayton', 'number' => '22', 'experience' => '1', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Darius Miller', 'team' => 'New Orleans Pelicans', 'position' => 'SF', 'college' => 'Kentucky', 'number' => '2', 'experience' => '1', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Tyreke Evans', 'team' => 'New Orleans Pelicans', 'position' => 'SF', 'college' => 'Memphis', 'number' => '1', 'experience' => '4', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Eric Gordon', 'team' => 'New Orleans Pelicans', 'position' => 'SG', 'college' => 'Indiana', 'number' => '10', 'experience' => '5', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Greg Stiemsma', 'team' => 'New Orleans Pelicans', 'position' => 'C', 'college' => 'Wisconsin', 'number' => '34', 'experience' => '2', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'James Johnson', 'team' => 'Memphis Grizzlies', 'position' => 'SF', 'college' => 'Wake Forest', 'number' => '3', 'experience' => '4', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Mike Miller', 'team' => 'Memphis Grizzlies', 'position' => 'SF', 'college' => 'Florida', 'number' => '13', 'experience' => '13', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Mike Conley', 'team' => 'Memphis Grizzlies', 'position' => 'PG', 'college' => 'Ohio State', 'number' => '11', 'experience' => '6', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Courtney Lee', 'team' => 'Memphis Grizzlies', 'position' => 'SG', 'college' => 'Western Kentucky', 'number' => '5', 'experience' => '5', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Tayshaun Prince', 'team' => 'Memphis Grizzlies', 'position' => 'SF', 'college' => 'Kentucky', 'number' => '21', 'experience' => '11', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Kosta Koufos', 'team' => 'Memphis Grizzlies', 'position' => 'C', 'college' => 'Ohio State', 'number' => '41', 'experience' => '5', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Ed Davis', 'team' => 'Memphis Grizzlies', 'position' => 'PF', 'college' => 'North Carolina', 'number' => '32', 'experience' => '3', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Jamaal Franklin', 'team' => 'Memphis Grizzlies', 'position' => 'SG', 'college' => 'San Diego State', 'number' => '22', 'experience' => '0', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Quincy Pondexter', 'team' => 'Memphis Grizzlies', 'position' => 'SF', 'college' => 'Washington', 'number' => '20', 'experience' => '3', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Jon Leuer', 'team' => 'Memphis Grizzlies', 'position' => 'PF', 'college' => 'Wisconsin', 'number' => '30', 'experience' => '2', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Zach Randolph', 'team' => 'Memphis Grizzlies', 'position' => 'PF', 'college' => 'Michigan State', 'number' => '50', 'experience' => '12', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Nick Calathes', 'team' => 'Memphis Grizzlies', 'position' => 'SG', 'college' => 'Florida', 'number' => '12', 'experience' => '0', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Tony Allen', 'team' => 'Memphis Grizzlies', 'position' => 'SG', 'college' => 'Oklahoma State', 'number' => '9', 'experience' => '9', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Jeremy Lin', 'team' => 'Houston Rockets', 'position' => 'PG', 'college' => 'Harvard', 'number' => '7', 'experience' => '3', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Terrence Jones', 'team' => 'Houston Rockets', 'position' => 'PF', 'college' => 'Kentucky', 'number' => '6', 'experience' => '1', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Robert Covington', 'team' => 'Houston Rockets', 'position' => 'SF', 'college' => 'Tennessee State', 'number' => '33', 'experience' => '0', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Chandler Parsons', 'team' => 'Houston Rockets', 'position' => 'SF', 'college' => 'Florida', 'number' => '25', 'experience' => '2', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Troy Daniels', 'team' => 'Houston Rockets', 'position' => 'SG', 'college' => 'VCU', 'number' => '30', 'experience' => '0', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Dexter Pittman', 'team' => 'Houston Rockets', 'position' => 'C', 'college' => 'Texas', 'number' => '0', 'experience' => '3', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Donatas Motiejunas', 'team' => 'Houston Rockets', 'position' => 'PF', 'college' => 'Kaunas (Lithuania)', 'number' => '20', 'experience' => '1', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Patrick Beverley', 'team' => 'Houston Rockets', 'position' => 'PG', 'college' => 'Arkansas', 'number' => '2', 'experience' => '1', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Jordan Hamilton', 'team' => 'Houston Rockets', 'position' => 'SF', 'college' => 'Texas', 'number' => '5', 'experience' => '2', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Isaiah Canaan', 'team' => 'Houston Rockets', 'position' => 'PG', 'college' => 'Murray State', 'number' => '1', 'experience' => '0', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'James Harden', 'team' => 'Houston Rockets', 'position' => 'SG', 'college' => 'Arizona State', 'number' => '13', 'experience' => '4', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Dwight Howard', 'team' => 'Houston Rockets', 'position' => 'C', 'college' => 'SW Atlanta Christian Academy (GA', 'number' => '12', 'experience' => '9', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Omer Asik', 'team' => 'Houston Rockets', 'position' => 'C', 'college' => 'Fenerbahce S.K.', 'number' => '3', 'experience' => '3', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Francisco Garcia', 'team' => 'Houston Rockets', 'position' => 'SG', 'college' => 'Louisville', 'number' => '32', 'experience' => '8', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Ish Smith', 'team' => 'Phoenix Suns', 'position' => 'PG', 'college' => 'Wake Forest', 'number' => '3', 'experience' => '3', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Dionte Christmas', 'team' => 'Phoenix Suns', 'position' => 'SG', 'college' => 'Temple', 'number' => '25', 'experience' => '0', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Gerald Green', 'team' => 'Phoenix Suns', 'position' => 'SG', 'college' => 'Gulf Shores Academy (TX)', 'number' => '14', 'experience' => '6', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Markieff Morris', 'team' => 'Phoenix Suns', 'position' => 'PF', 'college' => 'Kansas', 'number' => '11', 'experience' => '2', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Alex Len', 'team' => 'Phoenix Suns', 'position' => 'C', 'college' => 'Maryland', 'number' => '21', 'experience' => '0', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Leandro Barbosa', 'team' => 'Phoenix Suns', 'position' => 'SG', 'college' => 'Palmeiras (Brazil)', 'number' => '10', 'experience' => '10', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Shavlik Randolph', 'team' => 'Phoenix Suns', 'position' => 'PF', 'college' => 'Duke', 'number' => '43', 'experience' => '6', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Channing Frye', 'team' => 'Phoenix Suns', 'position' => 'PF', 'college' => 'Arizona', 'number' => '8', 'experience' => '7', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Marcus Morris', 'team' => 'Phoenix Suns', 'position' => 'PF', 'college' => 'Kansas', 'number' => '15', 'experience' => '2', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Archie Goodwin', 'team' => 'Phoenix Suns', 'position' => 'SG', 'college' => 'Kentucky', 'number' => '20', 'experience' => '0', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Emeka Okafor', 'team' => 'Phoenix Suns', 'position' => 'C', 'college' => 'Connecticut', 'number' => '50', 'experience' => '9', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Miles Plumlee', 'team' => 'Phoenix Suns', 'position' => 'C', 'college' => 'Duke', 'number' => '22', 'experience' => '1', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Eric Bledsoe', 'team' => 'Phoenix Suns', 'position' => 'PG', 'college' => 'Kentucky', 'number' => '2', 'experience' => '3', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'P.J. Tucker', 'team' => 'Phoenix Suns', 'position' => 'SF', 'college' => 'Texas', 'number' => '17', 'experience' => '2', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Goran Dragic', 'team' => 'Phoenix Suns', 'position' => 'PG', 'college' => 'Union Olimpija', 'number' => '1', 'experience' => '5', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'DeAndre Jordan', 'team' => 'Los Angeles Clippers', 'position' => 'C', 'college' => 'Texas A&M', 'number' => '6', 'experience' => '4', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Jared Dudley', 'team' => 'Los Angeles Clippers', 'position' => 'SF', 'college' => 'Boston College', 'number' => '9', 'experience' => '6', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Blake Griffin', 'team' => 'Los Angeles Clippers', 'position' => 'PF', 'college' => 'Oklahoma', 'number' => '32', 'experience' => '3', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Ryan Hollins', 'team' => 'Los Angeles Clippers', 'position' => 'C', 'college' => 'UCLA', 'number' => '15', 'experience' => '7', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Reggie Bullock', 'team' => 'Los Angeles Clippers', 'position' => 'SG', 'college' => 'North Carolina', 'number' => '25', 'experience' => '0', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Danny Granger', 'team' => 'Los Angeles Clippers', 'position' => 'SF', 'college' => 'New Mexico', 'number' => '33', 'experience' => '8', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Willie Green', 'team' => 'Los Angeles Clippers', 'position' => 'SG', 'college' => 'Detroit Mercy', 'number' => '34', 'experience' => '10', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Jamal Crawford', 'team' => 'Los Angeles Clippers', 'position' => 'SG', 'college' => 'Michigan', 'number' => '11', 'experience' => '13', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Hedo Turkoglu', 'team' => 'Los Angeles Clippers', 'position' => 'SF', 'college' => 'Efes Pilsen', 'number' => '8', 'experience' => '13', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Chris Paul', 'team' => 'Los Angeles Clippers', 'position' => 'PG', 'college' => 'Wake Forest', 'number' => '3', 'experience' => '8', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Matt Barnes', 'team' => 'Los Angeles Clippers', 'position' => 'SF', 'college' => 'UCLA', 'number' => '22', 'experience' => '10', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Glen Davis', 'team' => 'Los Angeles Clippers', 'position' => 'PF', 'college' => 'Louisiana State', 'number' => '0', 'experience' => '6', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'J.J. Redick', 'team' => 'Los Angeles Clippers', 'position' => 'SG', 'college' => 'Duke', 'number' => '4', 'experience' => '7', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Darren Collison', 'team' => 'Los Angeles Clippers', 'position' => 'PG', 'college' => 'UCLA', 'number' => '2', 'experience' => '4', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Chase Budinger', 'team' => 'Minnesota Timberwolves', 'position' => 'SF', 'college' => 'Arizona', 'number' => '10', 'experience' => '4', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Corey Brewer', 'team' => 'Minnesota Timberwolves', 'position' => 'SF', 'college' => 'Florida', 'number' => '13', 'experience' => '6', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Dante Cunningham', 'team' => 'Minnesota Timberwolves', 'position' => 'PF', 'college' => 'Villanova', 'number' => '33', 'experience' => '4', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Kevin Martin', 'team' => 'Minnesota Timberwolves', 'position' => 'SG', 'college' => 'Western Carolina', 'number' => '23', 'experience' => '9', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Kevin Love', 'team' => 'Minnesota Timberwolves', 'position' => 'PF', 'college' => 'UCLA', 'number' => '42', 'experience' => '5', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Ronny Turiaf', 'team' => 'Minnesota Timberwolves', 'position' => 'C', 'college' => 'Gonzaga', 'number' => '32', 'experience' => '8', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Robbie Hummel', 'team' => 'Minnesota Timberwolves', 'position' => 'SF', 'college' => 'Purdue', 'number' => '6', 'experience' => '0', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Ricky Rubio', 'team' => 'Minnesota Timberwolves', 'position' => 'PG', 'college' => 'FC Barcelona', 'number' => '9', 'experience' => '2', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Luc Mbah a Moute', 'team' => 'Minnesota Timberwolves', 'position' => 'PF', 'college' => 'UCLA', 'number' => '12', 'experience' => '5', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Jose Barea', 'team' => 'Minnesota Timberwolves', 'position' => 'PG', 'college' => 'Northeastern', 'number' => '11', 'experience' => '7', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Shabazz Muhammad', 'team' => 'Minnesota Timberwolves', 'position' => 'SF', 'college' => 'UCLA', 'number' => '15', 'experience' => '0', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Nikola Pekovic', 'team' => 'Minnesota Timberwolves', 'position' => 'C', 'college' => 'Montenegro', 'number' => '14', 'experience' => '3', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Othyus Jeffers', 'team' => 'Minnesota Timberwolves', 'position' => 'SG', 'college' => 'Robert Morris (IL)', 'number' => '0', 'experience' => '2', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Gorgui Dieng', 'team' => 'Minnesota Timberwolves', 'position' => 'C', 'college' => 'Louisville', 'number' => '5', 'experience' => '0', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Jeremy Evans', 'team' => 'Utah Jazz', 'position' => 'SF', 'college' => 'Western Kentucky', 'number' => '40', 'experience' => '3', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'John Lucas III', 'team' => 'Utah Jazz', 'position' => 'PG', 'college' => 'Oklahoma State', 'number' => '5', 'experience' => '5', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Richard Jefferson', 'team' => 'Utah Jazz', 'position' => 'SF', 'college' => 'Arizona', 'number' => '24', 'experience' => '12', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Brandon Rush', 'team' => 'Utah Jazz', 'position' => 'SG', 'college' => 'Kansas', 'number' => '25', 'experience' => '5', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Trey Burke', 'team' => 'Utah Jazz', 'position' => 'PG', 'college' => 'Michigan', 'number' => '3', 'experience' => '0', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Enes Kanter', 'team' => 'Utah Jazz', 'position' => 'C', 'college' => 'Kentucky', 'number' => '0', 'experience' => '2', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Erik Murphy', 'team' => 'Utah Jazz', 'position' => 'PF', 'college' => 'Florida', 'number' => '33', 'experience' => '0', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Alec Burks', 'team' => 'Utah Jazz', 'position' => 'SG', 'college' => 'Colorado', 'number' => '10', 'experience' => '2', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Malcolm Thomas', 'team' => 'Utah Jazz', 'position' => 'PF', 'college' => 'San Diego State', 'number' => '22', 'experience' => '2', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Ian Clark', 'team' => 'Utah Jazz', 'position' => 'SG', 'college' => 'Belmont', 'number' => '21', 'experience' => '0', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Gordon Hayward', 'team' => 'Utah Jazz', 'position' => 'SG', 'college' => 'Butler', 'number' => '20', 'experience' => '3', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Derrick Favors', 'team' => 'Utah Jazz', 'position' => 'PF', 'college' => 'Georgia Tech', 'number' => '15', 'experience' => '3', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Marvin Williams', 'team' => 'Utah Jazz', 'position' => 'PF', 'college' => 'North Carolina', 'number' => '2', 'experience' => '8', 'created_at' => $now, 'updated_at' => $now),
            array('name' => 'Diante Garrett', 'team' => 'Utah Jazz', 'position' => 'PG', 'college' => 'Iowa State', 'number' => '8', 'experience' => '1', 'created_at' => $now, 'updated_at' => $now)
        );
    }

}
